modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="music_additions"
version="1.0.0"
displayName="Music Additions"
credits="CKatelin"
authors="Katelin"

[[dependencies.music_additions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




